# Generated by Django 6.0.6 on 2026-06-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('origin_id', models.AutoField(primary_key=True, serialize=False)),
                ('origin_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'origin',
            },
        ),
    ]
