# Generated by Django 6.0.6 on 2026-06-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('origin', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_name', models.CharField(db_index=True, max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('lead_message', models.CharField(blank=True, max_length=500, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin', models.ForeignKey(db_column='origin_id', on_delete=django.db.models.deletion.CASCADE, to='origin.origin')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='status.status')),
            ],
            options={
                'db_table': 'leads',
            },
        ),
    ]
